updates:
  - directory: /
    open-pull-requests-limit: 16
    package-ecosystem: github-actions
    schedule:
      interval: monthly
    target-branch: main
  - directory: /
    open-pull-requests-limit: 16
    package-ecosystem: npm
    schedule:
      interval: weekly
    target-branch: main
version: 2
